# Generated by Django 4.1.2 on 2022-10-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_id',
            field=models.ManyToManyField(blank=True, related_name='categories', to='common.category', verbose_name='Categories'),
        ),
    ]
