# Generated by Django 4.1.2 on 2022-11-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
